//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ikeepfitEntities1 : DbContext
    {
        public ikeepfitEntities1()
            : base("name=ikeepfitEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mt_plan> mt_plan { get; set; }
        public virtual DbSet<mt_knowledge> mt_knowledge { get; set; }
        public virtual DbSet<mt_course> mt_course { get; set; }
        public virtual DbSet<mt_article> mt_article { get; set; }
        public virtual DbSet<mt_articletype> mt_articletype { get; set; }
    }
}
