//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_food
    {
        public string mt_food_id { get; set; }
        public string mt_foodtype_id { get; set; }
        public string mt_food_remarks { get; set; }
        public string mt_food_heat { get; set; }
        public string mt_food_prptein { get; set; }
        public string mt_food_ch { get; set; }
        public string mt_food_fat { get; set; }
        public string mt_food_cholesterol { get; set; }
        public string mt_food_Mg { get; set; }
        public string mt_food_Ca { get; set; }
        public string mt_food_Fe { get; set; }
        public string mt_food_Zn { get; set; }
        public string mt_food_Cu { get; set; }
        public string mt_food_Mn { get; set; }
        public string mt_food_Ka { get; set; }
        public string mt_food_fibrin { get; set; }
        public string mt_food_va { get; set; }
        public string mt_food_vc { get; set; }
        public string mt_food_ve { get; set; }
        public string mt_food_carotin { get; set; }
        public string Column_21 { get; set; }
    
        public virtual mt_foodtype mt_foodtype { get; set; }
    }
}
