//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_knowledgemark
    {
        public string mt_knowledgemark_id { get; set; }
        public string mt_knowledge_id { get; set; }
        public string mt_mark_id { get; set; }
    
        public virtual mt_knowledge mt_knowledge { get; set; }
        public virtual mt_mark mt_mark { get; set; }
    }
}
