//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_user
    {
        public mt_user()
        {
            this.mt_article = new HashSet<mt_article>();
            this.mt_user_course = new HashSet<mt_user_course>();
            this.mt_user_collection = new HashSet<mt_user_collection>();
            this.mt_user_plan = new HashSet<mt_user_plan>();
            this.mt_userfans = new HashSet<mt_userfans>();
            this.mt_userlike = new HashSet<mt_userlike>();
        }
    
        public string mt_user_id { get; set; }
        public string mt_user_name { get; set; }
        public string mt_user_pwd { get; set; }
        public string mt_user_email { get; set; }
        public Nullable<double> mt_user_height { get; set; }
        public Nullable<double> mt_user_weight { get; set; }
        public Nullable<System.DateTime> mt_user_birth { get; set; }
        public Nullable<double> mt_user_bodyfat { get; set; }
        public byte[] mt_user_icon { get; set; }
    
        public virtual ICollection<mt_article> mt_article { get; set; }
        public virtual ICollection<mt_user_course> mt_user_course { get; set; }
        public virtual ICollection<mt_user_collection> mt_user_collection { get; set; }
        public virtual ICollection<mt_user_plan> mt_user_plan { get; set; }
        public virtual ICollection<mt_userfans> mt_userfans { get; set; }
        public virtual ICollection<mt_userlike> mt_userlike { get; set; }
    }
}
