//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ikeepfitEntities : DbContext
    {
        public ikeepfitEntities()
            : base("name=ikeepfitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mt_article> mt_article { get; set; }
        public DbSet<mt_articletype> mt_articletype { get; set; }
        public DbSet<mt_course> mt_course { get; set; }
        public DbSet<mt_course_day> mt_course_day { get; set; }
        public DbSet<mt_food> mt_food { get; set; }
        public DbSet<mt_foodtype> mt_foodtype { get; set; }
        public DbSet<mt_knowledge> mt_knowledge { get; set; }
        public DbSet<mt_knowledgemark> mt_knowledgemark { get; set; }
        public DbSet<mt_mark> mt_mark { get; set; }
        public DbSet<mt_plan> mt_plan { get; set; }
        public DbSet<mt_planday> mt_planday { get; set; }
        public DbSet<mt_planmark> mt_planmark { get; set; }
        public DbSet<mt_user> mt_user { get; set; }
        public DbSet<mt_user_collection> mt_user_collection { get; set; }
        public DbSet<mt_user_course> mt_user_course { get; set; }
        public DbSet<mt_user_plan> mt_user_plan { get; set; }
        public DbSet<mt_userfans> mt_userfans { get; set; }
        public DbSet<mt_userlike> mt_userlike { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
