//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_planday
    {
        public string mt_plan_id { get; set; }
        public string mt_planday_id { get; set; }
        public Nullable<int> mt_planday_day { get; set; }
        public string mt_planday_title { get; set; }
        public string mt_planday_remarks { get; set; }
        public string mt_planday_video { get; set; }
        public string mt_planday_step { get; set; }
        public string mt_planday_kcalorie { get; set; }
    
        public virtual mt_plan mt_plan { get; set; }
    }
}
