//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_user_plan
    {
        public string mt_plan_id { get; set; }
        public string mt_user_planid { get; set; }
        public Nullable<int> mt_user_plankday { get; set; }
        public Nullable<int> mt_user_plankweek { get; set; }
        public string mt_user_planktime { get; set; }
        public string mt_user_plankcalorie { get; set; }
        public string mt_user_id { get; set; }
    
        public virtual mt_user mt_user { get; set; }
    }
}
