//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_plan
    {
        public string mt_plan_id { get; set; }
        public string mt_plan_name { get; set; }
        public string mt_plan_title { get; set; }
        public string mt_plan_remarks { get; set; }
        public Nullable<int> mt_plan_week { get; set; }
        public Nullable<int> mt_plan_day { get; set; }
        public string mt_plan_strength { get; set; }
    }
}
