//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikeepfit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_knowledge
    {
        public mt_knowledge()
        {
            this.mt_knowledgemark = new HashSet<mt_knowledgemark>();
        }
    
        public string mt_knowledge_id { get; set; }
        public string mt_knowledge_title { get; set; }
        public Nullable<System.DateTime> mt_knowledge_time { get; set; }
        public string mt_knowledge_remarks { get; set; }
        public string mt_knowledge_content { get; set; }
    
        public virtual ICollection<mt_knowledgemark> mt_knowledgemark { get; set; }
    }
}
